## Ejercicio 3

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from lista4.data import load_csv
from lista4.models import fit_linear
from lista4.metrics import empirical_risk_squared

pd.set_option("display.float_format", lambda v: f"{v:,.6f}")

In [2]:
df3 = load_csv("experimento_3.csv")
df3["z2"] = df3["x2"] / 100.0

m1 = fit_linear(df3, ["x1", "x2"])   # y = β0 + β1 x1 + β2 x2
m2 = fit_linear(df3, ["x1", "z2"])   # y = γ0 + γ1 x1 + γ2 z2

y1 = m1.predict(df3[["x1", "x2"]])
y2 = m2.predict(df3[["x1", "z2"]])

R1 = empirical_risk_squared(df3["y"], y1)
R2 = empirical_risk_squared(df3["y"], y2)

In [3]:
tabla_a3 = pd.DataFrame([
    {"modelo": "β (x1, x2)", "intercepto": m1.intercept,
     "coef_x1": m1.coefs[0], "coef_2": m1.coefs[1], "R": R1},
    {"modelo": "γ (x1, z2)", "intercepto": m2.intercept,
     "coef_x1": m2.coefs[0], "coef_2": m2.coefs[1], "R": R2},
])
tabla_a3

       modelo  intercepto  coef_x1   coef_2        R
0  β (x1, x2)   -0.101470 5.012066 0.050477 0.923225
1  γ (x1, z2)   -0.101470 5.012066 5.047693 0.923225

In [4]:
d = np.abs(y1 - y2)
max_d = float(d.max())
print(f"max_i d_i = {max_d:.3e}")

max_i d_i = 7.161e-15

In [5]:
err_b0 = abs(m2.intercept - m1.intercept)
err_b1 = abs(m2.coefs[0] - m1.coefs[0])
err_b2 = abs(m2.coefs[1] - 100 * m1.coefs[1])

pd.DataFrame({
    "comparación": ["γ0 ≈ β0", "γ1 ≈ β1", "γ2 ≈ 100·β2"],
    "error_absoluto": [err_b0, err_b1, err_b2],
})

   comparación  error_absoluto
0      γ0 ≈ β0        0.000000
1      γ1 ≈ β1        0.000000
2  γ2 ≈ 100·β2        0.000000

In [6]:
print(f"|β2| = {abs(m1.coefs[1]):.6f}")
print(f"|γ2| = {abs(m2.coefs[1]):.6f}")
print(f"|γ2| / |β2| = {abs(m2.coefs[1]) / abs(m1.coefs[1]):.4f}  (esperado ≈ 100)")
print(f"max_i d_i (recordatorio) = {max_d:.3e}")

|β2| = 0.050477
|γ2| = 5.047693
|γ2| / |β2| = 100.0000  (esperado ≈ 100)
max_i d_i (recordatorio) = 7.161e-15

In [7]:
tabla_e3 = pd.DataFrame([
    {"modelo": "β", "intercepto": m1.intercept, "coef_x1": m1.coefs[0],
     "coef_x2_o_z2": m1.coefs[1], "R": R1, "max_d": max_d},
    {"modelo": "γ", "intercepto": m2.intercept, "coef_x1": m2.coefs[0],
     "coef_x2_o_z2": m2.coefs[1], "R": R2, "max_d": max_d},
])
tabla_e3

  modelo  intercepto  coef_x1  coef_x2_o_z2        R    max_d
0      β   -0.101470 5.012066      0.050477 0.923225 0.000000
1      γ   -0.101470 5.012066      5.047693 0.923225 0.000000